#!/usr/bin/env python3
"""Convert downloaded brand SVG logos (firmware/tools/logos/*.svg) into
RGB565 C arrays (firmware/src/assets/logos.h) for the VibeStick firmware.

Sources (see logos/):
  claude.svg    - simpleicons.org (brand fill #D97757 kept as-is)
  kimi.svg      - simpleicons.org (black -> tinted)
  opencode.svg  - simpleicons.org (black -> tinted)
  openai_knot.svg - cdnlogo.com OpenAI knot glyph (black -> tinted)
  bluetooth.svg - simpleicons.org Bluetooth rune (black -> tinted)

Draw with:  M5.Lcd.pushImage(x, y, W, H, icon, ICON_TRANSPARENT);

Regenerate:  firmware/tools/.venv/bin/python firmware/tools/gen_logos.py
(preview sheet written to firmware/tools/logos_preview.png)
"""

import io
import os

import cairosvg
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.join(HERE, "..", "src", "assets", "logos.h")
PREVIEW = os.path.join(HERE, "logos_preview.png")

TRANSPARENT = 0xF81F  # magenta sentinel, matches icons.h

# name -> (svg file, size, RGB tint or None to keep source colors)
ICONS = {
    "logo_claude": ("claude.svg", 24, None),           # brand orange baked in
    "logo_codex": ("openai_knot.svg", 24, (255, 255, 255)),
    "logo_opencode": ("opencode.svg", 24, (255, 255, 255)),
    "logo_kimi": ("kimi.svg", 24, (96, 165, 250)),     # light blue
    "logo_bt": ("bluetooth.svg", 16, (0, 130, 252)),   # bluetooth blue
    "logo_bt_large": ("bluetooth.svg", 32, (0, 130, 252)),
}


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def render(svg_path: str, size: int) -> Image.Image:
    png = cairosvg.svg2png(url=svg_path, output_width=size * 8,
                           output_height=size * 8)
    img = Image.open(io.BytesIO(png)).convert("RGBA")
    # fit to square canvas (logos are square-ish; knot is near-square)
    w, h = img.size
    side = max(w, h)
    canvas = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    canvas.paste(img, ((side - w) // 2, (side - h) // 2), img)
    return canvas.resize((size, size), Image.LANCZOS)


def to_pixels(img: Image.Image, size: int, tint):
    px = img.load()
    out = []
    for y in range(size):
        for x in range(size):
            r, g, b, a = px[x, y]
            if a < 128:
                out.append(TRANSPARENT)
            elif tint is not None:
                out.append(rgb565(*tint))
            else:
                out.append(rgb565(r, g, b))
    return out


def main() -> None:
    arrays = {}
    previews = []
    for name, (svg, size, tint) in ICONS.items():
        path = os.path.join(HERE, "logos", svg)
        img = render(path, size)
        pixels = to_pixels(img, size, tint)
        arrays[name] = (size, pixels)
        # preview from the FINAL pixel data (tints applied), on dark bg
        prev = Image.new("RGB", (size, size), (24, 24, 32))
        ppx = prev.load()
        for y in range(size):
            for x in range(size):
                p = pixels[y * size + x]
                if p != TRANSPARENT:
                    ppx[x, y] = ((p >> 8) & 0xF8, (p >> 3) & 0xFC, (p << 3) & 0xF8)
        previews.append((name, prev.resize((size * 8, size * 8), Image.NEAREST)))

    with open(OUT_H, "w") as f:
        f.write("// AUTO-GENERATED by firmware/tools/gen_logos.py -- do not edit by hand.\n")
        f.write("// Real brand logos converted from firmware/tools/logos/*.svg\n")
        f.write("// 16-bit RGB565 bitmaps; draw with:\n")
        f.write("//   M5.Lcd.pushImage(x, y, W, H, icon, ICON_TRANSPARENT);\n")
        f.write("#pragma once\n\n#include <stdint.h>\n\n")
        f.write("// ICON_TRANSPARENT (0xF81F) is defined in icons.h\n\n")
        for name, (size, pixels) in arrays.items():
            f.write(f"static const uint16_t {name}[{size * size}] = {{\n")
            for y in range(size):
                row = ",".join(f"0x{p:04X}" for p in pixels[y * size:(y + 1) * size])
                f.write(f"  {row},\n")
            f.write("};\n\n")

    # contact-sheet preview
    pad = 12
    w = sum(p.width for _, p in previews) + pad * (len(previews) + 1)
    h = max(p.height for _, p in previews) + pad * 2
    sheet = Image.new("RGBA", (w, h), (24, 24, 32, 255))
    x = pad
    for _, p in previews:
        sheet.paste(p, (x, pad))
        x += p.width + pad
    sheet.save(PREVIEW)
    print(f"wrote {OUT_H} and {PREVIEW}")
    print("icons:", ", ".join(arrays))


if __name__ == "__main__":
    main()
