#!/usr/bin/env python3
"""Generate firmware/src/assets/cjk_font.h -- a 16 px bitmap font covering
ASCII (8x16 half-width) and the GB2312 level-1 hanzi set (3755 glyphs,
16x16 full-width) for the VibeStick firmware.

Font source: Noto Sans CJK SC (SIL Open Font License 1.1,
https://github.com/notofonts/noto-cjk), rasterized locally from
/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc -- OFL allows
embedding/subsetting. No network access is needed at build time; the
generated header is committed to the repo.

The GB2312 level-1 set is derived programmatically (rows 0xB0-0xD7 of the
GB2312 encoding, decoded with Python's gb2312 codec -> exactly 3755 chars).

Regenerate:  python3 firmware/tools/gen_cjk_font.py
"""

import os

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_H = os.path.normpath(os.path.join(HERE, "..", "src", "assets", "cjk_font.h"))
PREVIEW = os.path.join(HERE, "cjk_font_preview.png")

TTC = "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc"
FONT_SIZE = 15  # Noto CJK ink box ~0.88em -> 15 px fits the 16 px cell

GLYPH_W, GLYPH_H = 16, 16
ASCII_W = 8


def gb2312_level1():
    """GB2312 rows 16-55 = level-1 hanzi (3755 chars, sorted by codepoint)."""
    chars = []
    for hi in range(0xB0, 0xD8):
        for lo in range(0xA1, 0xFF):
            try:
                chars.append(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return sorted(ord(c) for c in chars)


def pick_face(path):
    """Find the SC face index inside the TTC (falls back to 0)."""
    for idx in range(16):
        try:
            f = ImageFont.truetype(path, FONT_SIZE, index=idx)
        except Exception:
            break
        name = " ".join(f.getname())
        if "SC" in name:
            print(f"using face {idx}: {name}")
            return idx
    print("SC face not found, using face 0")
    return 0


def rasterize(font, ch, width):
    """Render one glyph into a width x 16 box.

    Returns row bytes (MSB left), nbytes = ceil(width/8) per row:
    1 byte/row for 8 px ASCII, 2 bytes/row for 16 px hanzi.
    """
    img = Image.new("L", (width, GLYPH_H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, -2), ch, fill=255, font=font)
    nbytes = (width + 7) // 8
    out = []
    for y in range(GLYPH_H):
        for b in range(nbytes):
            val = 0
            for x in range(b * 8, min(b * 8 + 8, width)):
                if img.getpixel((x, y)) >= 128:
                    val |= 0x80 >> (x % 8)
            out.append(val)
    return out


def rasterize_ascii(font, ch):
    """8x16 ASCII glyph, ink centered horizontally. Rendered at a smaller
    size (12 px) so wide letters fit the box without cropping."""
    img = Image.new("L", (32, GLYPH_H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, -2), ch, fill=255, font=font)
    bbox = img.getbbox()
    if bbox is None:
        ink = Image.new("L", (1, 1), 0)
    else:
        ink = img.crop(bbox)
    if ink.width > ASCII_W:  # right-crop only: keep the left leg intact
        ink = ink.crop((0, 0, ASCII_W, ink.height))
    cell = Image.new("L", (ASCII_W, GLYPH_H), 0)
    cell.paste(ink, ((ASCII_W - ink.width) // 2, 0))
    out = []
    for y in range(GLYPH_H):
        val = 0
        for x in range(ASCII_W):
            if cell.getpixel((x, y)) >= 128:
                val |= 0x80 >> x
        out.append(val)
    return out


def main():
    hanzi = gb2312_level1()
    face = pick_face(TTC)
    font = ImageFont.truetype(TTC, FONT_SIZE, index=face)

    ascii_cps = list(range(0x20, 0x7F))
    ascii_glyphs = [rasterize_ascii(font, chr(cp)) for cp in ascii_cps]
    hanzi_glyphs = [rasterize(font, chr(cp), GLYPH_W) for cp in hanzi]

    with open(OUT_H, "w") as f:
        f.write("// AUTO-GENERATED by firmware/tools/gen_cjk_font.py -- do not edit.\n")
        f.write("// 16 px bitmap font: ASCII 8x16 half-width + GB2312 level-1\n")
        f.write("// hanzi 16x16 full-width. Source: Noto Sans CJK SC (SIL OFL 1.1).\n")
        f.write("// Row-major, MSB left. Lookup: binary search cjk_hanzi_index.\n")
        f.write("#pragma once\n\n#include <stdint.h>\n\n")
        f.write(f"#define CJK_FONT_ASCII_COUNT {len(ascii_cps)}\n")
        f.write(f"#define CJK_FONT_HANZI_COUNT {len(hanzi)}\n\n")

        f.write(f"static const uint8_t cjk_ascii_glyphs[{len(ascii_cps) * 16}] = {{\n")
        for rows in ascii_glyphs:
            f.write("  " + ",".join(f"0x{b:02X}" for b in rows) + ",\n")
        f.write("};\n\n")

        f.write(f"static const uint16_t cjk_hanzi_index[{len(hanzi)}] = {{\n")
        for i in range(0, len(hanzi), 16):
            f.write("  " + ",".join(f"0x{cp:04X}" for cp in hanzi[i:i + 16]) + ",\n")
        f.write("};\n\n")

        f.write(f"static const uint8_t cjk_hanzi_glyphs[{len(hanzi) * 32}] = {{\n")
        for rows in hanzi_glyphs:  # 32 bytes per glyph (2 per row)
            f.write("  " + ",".join(f"0x{b:02X}" for b in rows) + ",\n")
        f.write("};\n")

    # Preview sheet: ASCII sample + first/picked hanzi
    sample_cp = [ord(c) for c in "VibeStick 你好，世界！修复登录 继续测试 0123 ?"]
    cell = 20
    sheet = Image.new("RGB", (16 * cell, ((len(sample_cp) + 15) // 16) * cell),
                      (24, 24, 32))
    font_prev = ImageFont.truetype(TTC, FONT_SIZE, index=face)
    for i, cp in enumerate(sample_cp):
        img = Image.new("L", (GLYPH_W, GLYPH_H), 0)
        d = ImageDraw.Draw(img)
        d.text((0, -2), chr(cp), fill=255, font=font_prev)
        x0, y0 = (i % 16) * cell + 2, (i // 16) * cell + 2
        for y in range(GLYPH_H):
            for x in range(GLYPH_W):
                if img.getpixel((x, y)) >= 128:
                    sheet.putpixel((x0 + x, y0 + y), (255, 255, 255))
    sheet.save(PREVIEW)
    size = os.path.getsize(OUT_H)
    print(f"wrote {OUT_H} ({size} bytes, {len(hanzi)} hanzi + {len(ascii_cps)} ascii)")
    print(f"preview: {PREVIEW}")


if __name__ == "__main__":
    main()
