#!/usr/bin/env python3
"""Generate firmware/src/assets/cjk_font.h -- a 16 px bitmap font covering
ASCII (8x16 half-width) and the GB2312 level-1 hanzi set (3755 glyphs,
16x16 full-width) for the VibeStick firmware.

Font source: WenQuanYi Micro Hei (wqy-microhei.ttc), licensed under
GPLv3 with font-embedding exception (bitmap embedding explicitly allowed).
Obtained from the Debian package fonts-wqy-microhei:
  https://deb.debian.org/debian/pool/main/f/fonts-wqy-microhei/
Local path expected: firmware/tools/fonts/wqy-microhei.ttc
(download once with:  curl -sL -o /tmp/wqy.deb <deb url> && cd /tmp &&
 ar x wqy.deb data.tar.xz && tar -xf data.tar.xz && cp
 /tmp/usr/share/fonts/truetype/wqy/wqy-microhei.ttc
 firmware/tools/fonts/)
Same font family the u8g2 wqy16 bitmap fonts are derived from; metrics are
applied via a shared baseline anchor for unified EN/CJK rendering.

The GB2312 level-1 set is derived programmatically (rows 0xB0-0xD7 of the
GB2312 encoding, decoded with Python's gb2312 codec -> exactly 3755 chars).

Regenerate:  python3 firmware/tools/gen_cjk_font.py
"""

import os

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
TTC = os.path.join(HERE, "fonts", "wqy-microhei.ttc")
ASCII_TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
OUT_H = os.path.normpath(os.path.join(HERE, "..", "src", "assets", "cjk_font.h"))
PREVIEW = os.path.join(HERE, "cjk_font_preview.png")

FONT_SIZE = 14  # fits the 16 px cell with headroom; shared baseline below
ASCII_FONT_SIZE = 13  # true 8 px monospace advance; avoids cropping m/w
BASELINE = 13   # y of the baseline inside every 16 px row (both scripts)

GLYPH_W, GLYPH_H = 16, 16
ASCII_W = 8


def gb2312_level1():
    """GB2312 rows 16-55 = level-1 hanzi (3755 chars, sorted by codepoint)."""
    chars = []
    for hi in range(0xB0, 0xD8):
        for lo in range(0xA1, 0xFF):
            try:
                chars.append(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return sorted(ord(c) for c in chars)


def gb2312_symbols():
    """GB2312 rows 0xA1-0xAF: full-width punctuation, symbols, full-width
    ASCII/digits, kana, Greek, Russian, box-drawing. CLI output is full of
    these （，。：；？！“”（）【】《》、…— etc.)."""
    chars = []
    for hi in range(0xA1, 0xB0):
        for lo in range(0xA1, 0xFF):
            try:
                chars.append(bytes([hi, lo]).decode("gb2312"))
            except UnicodeDecodeError:
                pass
    return sorted(ord(c) for c in chars)


def rasterize(font, ch, width):
    """Render one glyph on the shared baseline, return row bytes (MSB left),
    ceil(width/8) bytes per row."""
    img = Image.new("L", (width, GLYPH_H), 0)
    d = ImageDraw.Draw(img)
    d.text((0, BASELINE), ch, fill=255, font=font, anchor="ls")
    nbytes = (width + 7) // 8
    out = []
    for y in range(GLYPH_H):
        for b in range(nbytes):
            val = 0
            for x in range(b * 8, min(b * 8 + 8, width)):
                if img.getpixel((x, y)) >= 128:
                    val |= 0x80 >> (x % 8)
            out.append(val)
    return out


def main():
    hanzi = sorted(set(gb2312_level1() + gb2312_symbols()))
    print(f"glyphs: {len(hanzi)} (level-1 hanzi + A1-AF symbols)")
    font = ImageFont.truetype(TTC, FONT_SIZE, index=0)
    ascii_font = ImageFont.truetype(ASCII_TTF, ASCII_FONT_SIZE)
    print("metrics:", font.getmetrics(), "ascii:", ascii_font.getmetrics())

    ascii_cps = list(range(0x20, 0x7F))
    ascii_glyphs = [rasterize(ascii_font, chr(cp), ASCII_W) for cp in ascii_cps]
    hanzi_glyphs = [rasterize(font, chr(cp), GLYPH_W) for cp in hanzi]

    with open(OUT_H, "w") as f:
        f.write("// AUTO-GENERATED by firmware/tools/gen_cjk_font.py -- do not edit.\n")
        f.write("// 16 px bitmap font: ASCII 8x16 half-width + GB2312 level-1\n")
        f.write("// hanzi 16x16 full-width, unified baseline (row 13).\n")
        f.write("// CJK: WenQuanYi Micro Hei; ASCII: DejaVu Sans Mono.\n")
        f.write("// Row-major, MSB left. Lookup: binary search cjk_hanzi_index.\n")
        f.write("#pragma once\n\n#include <stdint.h>\n\n")
        f.write(f"#define CJK_FONT_ASCII_COUNT {len(ascii_cps)}\n")
        f.write(f"#define CJK_FONT_HANZI_COUNT {len(hanzi)}\n\n")

        f.write(f"static const uint8_t cjk_ascii_glyphs[{len(ascii_cps) * 16}] = {{\n")
        for rows in ascii_glyphs:
            f.write("  " + ",".join(f"0x{b:02X}" for b in rows) + ",\n")
        f.write("};\n\n")

        f.write(f"static const uint16_t cjk_hanzi_index[{len(hanzi)}] = {{\n")
        for i in range(0, len(hanzi), 16):
            f.write("  " + ",".join(f"0x{cp:04X}" for cp in hanzi[i:i + 16]) + ",\n")
        f.write("};\n\n")

        f.write(f"static const uint8_t cjk_hanzi_glyphs[{len(hanzi) * 32}] = {{\n")
        for rows in hanzi_glyphs:  # 32 bytes per glyph (2 per row)
            f.write("  " + ",".join(f"0x{b:02X}" for b in rows) + ",\n")
        f.write("};\n")

    # Preview sheet: mixed sample rendered with the SAME pipeline semantics.
    sample = "VibeStick kimi 你好，世界！修复登录：《协议》v2.1（测试）…— 中英混排 baseline 0123 ?"
    cell = 20
    sheet = Image.new("RGB", (26 * cell, ((len(sample) + 25) // 26) * cell),
                      (24, 24, 32))
    for i, ch in enumerate(sample):
        img = Image.new("L", (GLYPH_W, GLYPH_H), 0)
        d = ImageDraw.Draw(img)
        d.text((0, BASELINE), ch, fill=255,
               font=ascii_font if ord(ch) < 0x7F else font, anchor="ls")
        x0, y0 = (i % 26) * cell + 2, (i // 26) * cell + 2
        for y in range(GLYPH_H):
            for x in range(GLYPH_W):
                if img.getpixel((x, y)) >= 128:
                    sheet.putpixel((x0 + x, y0 + y), (255, 255, 255))
    sheet.save(PREVIEW)
    size = os.path.getsize(OUT_H)
    print(f"wrote {OUT_H} ({size} bytes, {len(hanzi)} hanzi + {len(ascii_cps)} ascii)")
    print(f"preview: {PREVIEW}")


if __name__ == "__main__":
    main()
